language: elixir

elixir:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - 1.11
otp_release:
  - 19.3
  - 20.3
  - 21.3
  - 22.3

matrix:
  exclude:
    - elixir: 1.5
      otp_release: 21.3
    - elixir: 1.5
      otp_release: 22.3
    - elixir: 1.6
      otp_release: 22.3
    - elixir: 1.7
      otp_release: 19.3
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.9
      otp_release: 19.3
    - elixir: 1.10
      otp_release: 19.3
    - elixir: 1.10
      otp_release: 20.3
    - elixir: 1.11
      otp_release: 19.3
    - elixir: 1.11
      otp_release: 20.3
      